url: http://mdedotnet.co/
baseurl: ""

# Site settings
title: MDE.NET
email: mdedotnet@gmail.com
description: "MDE.NET es una comunidad para todos los desarrolladores y entusiastas del desarrollo que usan o desean aprender .Net y tecnologías Microsoft en general. Te invitamos a participar de nuestras reuniones, charlas, conferencias y talleres en los que podrás aprender y compartir sobre nuevas tecnologías."


# Team names, titles and social links
people:
- name: Geovanny Alzate S.
  pic: 1
  position: Guitarrista aficionado, mochilero profesional
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/geovannyalzatesandoval
    - title: facebook
      url: https://www.facebook.com/giovany.a.sandoval
    - title: stack-overflow
      url: https://stackoverflow.com/users/8121383/geovanny-alzate-sandoval
    - title: github
      url: https://github.com/vany0114/
    - title: rss
      url: http://elvanydev.com/

- name: Felipe Correa
  pic: 6
  position: Artesano de software, manoseador de guitarras y gamer.
  social:
    - title: twitter
      url: https://twitter.com/fcu423
    - title: stack-overflow
      url: https://stackoverflow.com/users/1388362/felipe-correa
    - title: linkedin
      url: https://www.linkedin.com/in/felipecorreau/

- name: Kevin Sejin
  pic: 3
  position: Software Developer, Traveler and Football Soccer Lover.
  social:
    - title: globe
      url: https://kevinricar24.github.io

- name: Roger Gómez
  pic: 4
  position: Simpsons' fan. Consumidor de deportes y conciertos de Rock.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/roger-gomez-jaramillo-45236b19/
    - title: github
      url: https://github.com/rgomezj
    - title: twitter
      url: https://twitter.com/rgomezj
    - title: facebook
      url: https://www.facebook.com/rogergomez780
    - title: rss
      url: https://rogergomez.azurewebsites.net/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mdedotnet
  - title: facebook
    url: https://www.facebook.com/mdedotnet/
  - title: instagram
    url: https://www.instagram.com/mdedotnet/
  - title: meetup
    url: https://www.meetup.com/preview/MDE-NET
  - title: github
    url: http://github.com/mdedotnet
  - title: slideshare
    url: https://slides.com/mdedotnet
  - title: youtube
    url: https://www.youtube.com/channel/UCgnt7WceyEgeEGArdkC9HHw  

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty